feat(yadm): add rye + nvm install to bootstrap script

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -14,70 +14,61 @@ echo "Init submodules"
 yadm submodule update --recursive --init
 
 yes_no() {
-	read -r -p "$1 [y/N] " response
-	case "$response" in
-	[yY][eE][sS] | [yY])
-		return 0
-		;;
-	*)
-		return 1
-		;;
-	esac
+  read -r -p "$1 [y/N] " response
+  case "$response" in
+  [yY][eE][sS] | [yY])
+    return 0
+    ;;
+  *)
+    return 1
+    ;;
+  esac
 }
 
 # install rust
 install_cargo() {
-	if ! yes_no "Install cargo/rustup?"; then
-		return
-	fi
+  if ! yes_no "Install cargo/rustup?"; then
+    return
+  fi
 
-	curl https://sh.rustup.rs -sSf | sh
-	crates=(zoxide git-delta bat exa starship)
-	for crate in "${crates[@]}"; do
-		if yes_no "Install '${crate}'?"; then
-			cargo install "${crate}"
-		fi
-	done
+  curl https://sh.rustup.rs -sSf | sh
 }
 
-#install tea
-install_tea() {
-	if ! yes_no "Install tea?"; then
-		return
-	fi
+install_rye() {
+  if ! yes_no "Install rye/python?"; then
+    return
+  fi
 
-	echo "installing tea"
-	sh <(curl tea.xyz) --yes
-	# packages=(lazygit nvim nushell cmake fd-find)
+  curl -sSf https://rye.astral.sh/get | bash
+}
 
-	# for package in "${packages[@]}"; do
-	# 	tea "${package}"
-	# done
-
-	# TODO:
-	# tea zoxide -- symlink/hardlink this bad boy
-	# tea cmake -- symlink/hardlink this bad boy
+install_nvm() {
+  if ! yes_no "Install nvm?"; then
+    return
+  fi
+  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
 }
 
 run_platform_specific_boostrap() {
-	# Directory to look for bootstrap executables in
-	BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+  # Directory to look for bootstrap executables in
+  BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
 
-	if [[ ! -d "$BOOTSTRAP_D" ]]; then
-		echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
-		exit 1
-	fi
+  if [[ ! -d "$BOOTSTRAP_D" ]]; then
+    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    exit 1
+  fi
 
-	find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
-		if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
-			if ! "$bootstrap"; then
-				echo "Error: bootstrap '$bootstrap' failed" >&2
-				exit 1
-			fi
-		fi
-	done
+  find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
+    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+      if ! "$bootstrap"; then
+        echo "Error: bootstrap '$bootstrap' failed" >&2
+        exit 1
+      fi
+    fi
+  done
 }
 
 install_cargo
-install_tea
+install_rye
+install_nvm
 run_platform_specific_boostrap
